# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  system,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.kernelPackages = pkgs.linuxKernel.packages.linux_zen;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ohci_pci"
    "ehci_pci"
    "virtio_pci"
    "ahci"
    "usbhid"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.kernelParams = [
    "pcie_port_pm=off"
    "pcie_aspm=1"
    "pcie_aspm.policy=performance"
    "amdgpu_aspm=1"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5e5cac24-b190-46ce-8eb7-826eeadf42db";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9CAC-D84F";
    fsType = "vfat";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s8.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault system;
}
